version: 0.2

phases:
  build:
    commands:
    ## Package pyspark
      - mkdir ./libs
      - pip install -U -r sparkapplication/requirements.txt -t ./libs
      - mkdir ./dist
      - cp main.py ./dist
      - cp -R streamsimulator ./dist
      - python -m  zipfile -c ./dist/sparkapplication.zip  sparkapplication/*
      - python -m  zipfile -c ./dist/boto3.zip ./libs/boto3/*
      - python -m  zipfile -c ./dist/boto.zip ./libs/boto/*
      - python -m  zipfile -c ./dist/botocore.zip ./libs/botocore/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  base-directory:
    - dist
