version: 0.2

phases:
  build:
    commands:
    ## Package pyspark
      - mkdir ./libs
      - pip install -U -r sparkapplication/requirements.txt -t ./libs
      - mkdir ./dist
      - cp sparkapplication/main.py ./dist
      - cp streamsimulator/* ./dist
      - python -m  zipfile -c jobs.zip  sparkapplication && mv jobs.zip ./dist/jobs.zip
      - python -m  zipfile -c libs.zip ./libs/* && mv libs.zip ./dist/libs.zip
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./dist/*.*
